name: Deploy Web

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: yarn hash:front
          restore-keys: yarn-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install-immutable
      
      - name: Pull mocks
        run: yarn mock simple-blog

      - name: Build website
        run: yarn build && yarn export
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .out
